FROM node
COPY package.json package.json
RUN npm install
COPY index.js index.js
CMD node index.js

ENV INFLUX_HOST "influx"
ENV INFLUX_DATABASE "telegraf"
ENV RUN_INTERVAL_MS "300000"
ENV LOAD_THRESHOLD "0.2"
ENV AWS_ACCESS_KEY_ID "CHANGE_ME"
ENV AWS_SECRET_ACCESS_KEY "CHANGE_ME"
ENV AWS_REGION "CHANGE_ME"
ENV TELEGRAF_HOST_PREFIX ""
